from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
CONFIG_PATH = PROJECT_ROOT / "config.env"

DEFAULT_CONFIG = {
    "LLM_PROVIDER": "deepseek",
    "DEEPSEEK_API_URL": "https://api.deepseek.com/v1/chat/completions",
    "DEEPSEEK_API_KEY": "",
    "DEEPSEEK_MODEL": "deepseek-chat",
    "DEEPSEEK_MAX_TOKENS": "512",
    "DEEPSEEK_TEMPERATURE": "0.2",
    "DATA_DIR": "data",
    "LOG_DIR": "logs",
}

PUBLIC_FIELDS = {
    "LLM_PROVIDER",
    "DEEPSEEK_API_URL",
    "DEEPSEEK_MODEL",
    "DEEPSEEK_MAX_TOKENS",
    "DEEPSEEK_TEMPERATURE",
    "DATA_DIR",
    "LOG_DIR",
}


def read_env_file(path=CONFIG_PATH):
    values = {}
    if not path.exists():
        return values

    with path.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip()
    return values


def read_config():
    config = DEFAULT_CONFIG.copy()
    config.update(read_env_file())
    return config


def apply_config_to_environment(config=None):
    config = config or read_config()
    for key in DEFAULT_CONFIG:
        value = str(config.get(key, "")).strip()
        if value:
            import os

            os.environ[key] = value
        else:
            import os

            os.environ.pop(key, None)


def save_config(updates, preserve_blank_api_key=True):
    current = read_config()
    next_config = current.copy()

    for key in DEFAULT_CONFIG:
        if key not in updates:
            continue
        value = str(updates.get(key, "")).strip()
        if key == "DEEPSEEK_API_KEY" and preserve_blank_api_key and not value:
            continue
        next_config[key] = value

    _validate_config(next_config)
    CONFIG_PATH.write_text(_serialize_config(next_config), encoding="utf-8")
    apply_config_to_environment(next_config)
    return next_config


def get_public_config(config=None):
    config = config or read_config()
    public = {key: config.get(key, "") for key in PUBLIC_FIELDS}
    public["DEEPSEEK_API_KEY_SET"] = bool(config.get("DEEPSEEK_API_KEY"))
    public["DEEPSEEK_API_KEY_PREVIEW"] = mask_secret(config.get("DEEPSEEK_API_KEY", ""))
    return public


def get_config_status(config=None):
    config = config or read_config()
    provider = config.get("LLM_PROVIDER", "deepseek").strip().lower()
    deepseek_configured = bool(
        config.get("DEEPSEEK_API_URL", "").strip()
        and config.get("DEEPSEEK_API_KEY", "").strip()
    )
    configured = provider == "mock" or deepseek_configured
    return {
        "configured": configured,
        "config_file_exists": CONFIG_PATH.exists(),
        "provider": provider,
        "deepseek_configured": deepseek_configured,
        "config": get_public_config(config),
    }


def mask_secret(value):
    if not value:
        return ""
    if len(value) <= 8:
        return "*" * len(value)
    return f"{value[:4]}...{value[-4:]}"


def _validate_config(config):
    provider = config.get("LLM_PROVIDER", "").strip().lower()
    if provider not in {"deepseek", "auto", "mock"}:
        raise ValueError("LLM_PROVIDER must be one of: deepseek, auto, mock")

    max_tokens = int(config.get("DEEPSEEK_MAX_TOKENS", "512"))
    if max_tokens <= 0:
        raise ValueError("DEEPSEEK_MAX_TOKENS must be greater than 0")

    temperature = float(config.get("DEEPSEEK_TEMPERATURE", "0.2"))
    if temperature < 0 or temperature > 2:
        raise ValueError("DEEPSEEK_TEMPERATURE must be between 0 and 2")


def _serialize_config(config):
    lines = [
        "# Medical Agent local model configuration.",
        "# Generated by the setup page. Keep this file private.",
        "",
    ]
    for key in DEFAULT_CONFIG:
        lines.append(f"{key}={config.get(key, '')}")
    return "\n".join(lines) + "\n"
