from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
CONFIG_PATH = PROJECT_ROOT / "config.env"

DEFAULT_CONFIG = {
    "LLM_PROVIDER": "deepseek",
    "DEEPSEEK_API_URL": "https://api.deepseek.com/v1/chat/completions",
    "DEEPSEEK_API_KEY": "",
    "DEEPSEEK_MODEL": "deepseek-chat",
    "DEEPSEEK_MAX_TOKENS": "512",
    "DEEPSEEK_TEMPERATURE": "0.2",
    "DASHSCOPE_API_KEY": "",
    "DASHSCOPE_VOICE_URL": "https://dashscope.aliyuncs.com/compatible-mode/v1",
    "DASHSCOPE_ASR_MODEL": "paraformer-v2",
    "DASHSCOPE_TTS_VOICE": "longwan",
    "DATA_DIR": "data",
    "LOG_DIR": "logs",
}

PUBLIC_FIELDS = {
    "LLM_PROVIDER",
    "DEEPSEEK_API_URL",
    "DEEPSEEK_MODEL",
    "DEEPSEEK_MAX_TOKENS",
    "DEEPSEEK_TEMPERATURE",
    "DASHSCOPE_VOICE_URL",
    "DASHSCOPE_ASR_MODEL",
    "DASHSCOPE_TTS_VOICE",
    "DATA_DIR",
    "LOG_DIR",
}

# 空值提交时须保留已有密钥的字段（配置页留空=不修改）
_BLANK_PRESERVED_KEYS = {"DEEPSEEK_API_KEY", "DASHSCOPE_API_KEY"}


def read_env_file(path=CONFIG_PATH):
    values = {}
    if not path.exists():
        return values

    with path.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip()
    return values


def read_config():
    config = DEFAULT_CONFIG.copy()
    config.update(read_env_file())
    return config


def apply_config_to_environment(config=None):
    config = config or read_config()
    # 应用全部配置键（含手填的可选键如 AMAP_API_KEY/HOSPITAL_DATA_URL），
    # web 配置页与序列化仍只管 DEFAULT_CONFIG 键
    for key, value in config.items():
        value = str(value).strip()
        if value:
            import os

            os.environ[key] = value
        else:
            import os

            os.environ.pop(key, None)


def save_config(updates, preserve_blank_api_key=True):
    current = read_config()
    next_config = current.copy()

    for key in DEFAULT_CONFIG:
        if key not in updates:
            continue
        value = str(updates.get(key, "")).strip()
        if key in _BLANK_PRESERVED_KEYS and preserve_blank_api_key and not value:
            continue
        next_config[key] = value

    _validate_config(next_config)
    CONFIG_PATH.write_text(_serialize_config(next_config), encoding="utf-8")
    apply_config_to_environment(next_config)
    return next_config


def get_public_config(config=None):
    config = config or read_config()
    public = {key: config.get(key, "") for key in PUBLIC_FIELDS}
    public["DEEPSEEK_API_KEY_SET"] = bool(config.get("DEEPSEEK_API_KEY"))
    public["DEEPSEEK_API_KEY_PREVIEW"] = mask_secret(config.get("DEEPSEEK_API_KEY", ""))
    public["DASHSCOPE_API_KEY_SET"] = bool(config.get("DASHSCOPE_API_KEY"))
    public["DASHSCOPE_API_KEY_PREVIEW"] = mask_secret(config.get("DASHSCOPE_API_KEY", ""))
    return public


def get_config_status(config=None):
    config = config or read_config()
    provider = config.get("LLM_PROVIDER", "deepseek").strip().lower()
    deepseek_configured = bool(
        config.get("DEEPSEEK_API_URL", "").strip()
        and config.get("DEEPSEEK_API_KEY", "").strip()
    )
    configured = provider == "mock" or deepseek_configured
    return {
        "configured": configured,
        "config_file_exists": CONFIG_PATH.exists(),
        "provider": provider,
        "deepseek_configured": deepseek_configured,
        "config": get_public_config(config),
    }


def mask_secret(value):
    if not value:
        return ""
    if len(value) <= 8:
        return "*" * len(value)
    return f"{value[:4]}...{value[-4:]}"


def _validate_config(config):
    provider = config.get("LLM_PROVIDER", "").strip().lower()
    if provider not in {"deepseek", "auto", "mock"}:
        raise ValueError("LLM_PROVIDER must be one of: deepseek, auto, mock")

    # 解析失败时给出含字段名的友好提示，避免前端只看到裸的 int()/float() 异常
    try:
        max_tokens = int(config.get("DEEPSEEK_MAX_TOKENS", "512"))
    except (TypeError, ValueError):
        raise ValueError("DEEPSEEK_MAX_TOKENS 必须为正整数")
    if max_tokens <= 0:
        raise ValueError("DEEPSEEK_MAX_TOKENS 必须为正整数")

    try:
        temperature = float(config.get("DEEPSEEK_TEMPERATURE", "0.2"))
    except (TypeError, ValueError):
        raise ValueError("DEEPSEEK_TEMPERATURE 必须为 0 到 2 之间的数字")
    if temperature < 0 or temperature > 2:
        raise ValueError("DEEPSEEK_TEMPERATURE 必须为 0 到 2 之间的数字")


def _serialize_config(config):
    lines = [
        "# Medical Agent local model configuration.",
        "# Generated by the setup page. Keep this file private.",
        "",
    ]
    for key in DEFAULT_CONFIG:
        lines.append(f"{key}={config.get(key, '')}")
    # 手填可选键（AMAP_API_KEY/HOSPITAL_DATA_URL 等）不在配置页管理范围，
    # 但序列化须原样保留，否则配置页保存会清掉它们导致数据源静默降级
    extras = {
        key: value
        for key, value in config.items()
        if key not in DEFAULT_CONFIG and str(value).strip()
    }
    if extras:
        lines.append("")
        lines.append("# Optional manual keys (not managed by the web setup page, preserved as-is)")
        for key, value in extras.items():
            lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"
